name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build project
      run: |
        gradle wrapper
        bash gradlew build
    
    - name: Upload articact
      uses: actions/upload-artifact@v2
      with:
        path: app/build
        name: gradle

  naked:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    
    - name: Run naked script
      run: |
        chmod +x naked_ci.sh
        ./naked_ci.sh

    - name: Upload articact
      uses: actions/upload-artifact@v2
      with:
        path: out/output.apk
        name: naked
